connections {
  r1-r2 {
    version = 2
    mobike = no
    local_addrs = 100.64.1.1
    remote_addrs = 100.64.2.2
    proposals = aes256-sha256-modp2048

    local {
      auth = psk
      id = 100.64.1.1
    }
    remote {
      auth = psk
      id = 100.64.2.2
    }

    children {
      lan-to-lan {
        local_ts = 10.1.0.0/24
        remote_ts = 10.2.0.0/24
        esp_proposals = aes256-sha256-modp2048
        start_action = trap
        close_action = trap
      }
    }
  }
}

secrets {
  ike-r1-r2 {
    id-1 = 100.64.1.1
    id-2 = 100.64.2.2
    secret = "SuperSecret123"
  }
}
