FROM alpine:3.22

RUN apk add --no-cache \
    bash \
    bind-tools \
    busybox-extras \
    conntrack-tools \
    curl \
    iproute2 \
    iputils \
    nftables \
    tcpdump

CMD ["sleep", "infinity"]
